global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['host.docker.internal:9090']

- job_name: 'api-gateway'
  static_configs:
  - targets: 
    - host.docker.internal:3000

- job_name: 'user-service'
  static_configs:
  - targets: 
    - host.docker.internal:3001

- job_name: 'progress-service'
  static_configs:
  - targets: 
    - host.docker.internal:3002
    
- job_name: 'puzzle-service'
  static_configs:
  - targets: 
    - host.docker.internal:3003